### ISSUE TITLE
8.1.3 Roadmap

### ISSUE THREAD

**Issue by trainfarb** [deg-entreprises/D.8.1-Management-Platform#16]

**Comment by trainfarb** [comment]
## 8.1.3 v0.00.00 - Brainstorm Metadata Structure
### 2023 09 06
Roadmap is defined by nested meetings:
* Tier 0 Meeting - Github Organization - Full Open Source Platform Ecosystem Lifecycle
  * Tier 1 Meetings - GitHub Repository - Each platform / Longplay is a meeting
    * Tier 2 Meetings - GitHub Project - Each Project Metadata / epicPlaylist is a meeting
      * Tier 3 Meetings - GitHub SubProject - Each Project / verse is a meeting
        * Tier 4 Meetings - GitHub Issue - Each Issue / beatDrop is a meeting
          * Tier 5 Meetings - GitHub Comments - Each comment / beat is a meeting

- [ ] Create 8.1.3 v0.00 MVP Project
- [ ] Link to 8.1.3 v0.00 MVP Project here
- [ ] Add Patrick's Meeting to 8.1.3 v0.00 MVP Project
- [ ] Create rough draft of platform directory metadata that can be added to the repository so it's easily synced between ecosystems
- [ ] Add rough draft of platform directory metadata to ourStory

**Comment by trainfarb** [comment]
Quantum Pincer `to`: https://github.com/users/trainfarb/projects/1/views/1?pane=issue&itemId=37919626
